apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aviso-ecs-service
  title: ECS Service Deployment
  description: Create a new ECS service or trigger an existing deployment workflow
  tags:
    - aws
    - ecs
    - deployment
    - github-actions

spec:
  owner: team:platform
  type: service

  ############################
  # PARAMETERS
  ############################
  parameters:
    - title: Deployment Options
      required:
        - serviceMode
      properties:
        serviceMode:
          title: What do you want to do?
          type: string
          default: create
          enum: [create, trigger]
          enumNames:
            - Create a new ECS service
            - Trigger existing deployment workflow

        repoUrl:
          title: GitHub Repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: [github.com]
            requestUserPermission: [repo, workflow]

        environment:
          title: Environment
          type: string
          default: dev
          enum: [dev, staging, prod]

      dependencies:
        serviceMode:
          oneOf:
            # =====================================================
            # CREATE NEW ECS SERVICE
            # =====================================================
            - properties:
                serviceMode:
                  const: create
                
                commandOverride:
                  title: Container Command (Optional)
                  type: string
                  description: "e.g. celery -A app.worker worker -l info (Leave empty for default)"

                s3EnvBucket:
                  title: S3 Bucket for Env Files
                  type: string
                  default: "dev-aviso-fargate-service-env"

                s3EnvFolder:
                  title: S3 Folder for Env Files
                  type: string
                  description: "e.g. user-tracker-qa-env (We will append /.env automatically)"

                envFileContent:
                  title: .env File Content
                  type: string
                  description: "Paste the full content of your .env file here."
                  ui:widget: textarea
                  ui:options:
                    rows: 100
                    placeholder: |
                      # Example format:
                      DB_HOST=localhost
                      DB_PORT=5432
                      API_KEY=your-secret-key  

                logGroupName:
                  title: CloudWatch Log Group Name
                  type: string
                  default: "/ecs/my-new-service"  

                ecsCluster:
                  title: ECS Cluster
                  type: string

                ecsServiceName:
                  title: ECS Service Name
                  type: string

                ecsTaskDefName:
                  title: Task Definition Family Name
                  type: string
                  description: "Must end with -td (e.g., my-service-td)"
                  default: "my-service-td"  

                ecrRepository:
                  title: ECR Repository Name
                  type: string

                containerName:
                  title: Container Name
                  type: string
                  default: app

                containerPort:
                  title: Container Port
                  type: number
                  default: 8000
                  description: Port on which the container listens  

                containerImage:
                  title: Container Image
                  type: string

                cpu:
                  title: vCPU Units
                  type: string
                  default: "512"
                  enum: ["256", "512", "1024", "2048", "4096"]

                memory:
                  title: Memory (MB)
                  type: string
                  default: "1024"
                  enum: ["512", "1024", "2048", "4096", "8192"]

                awsRegion:
                  title: AWS Region
                  type: string
                  default: us-east-1

                tags:
                  title: Resource Tags
                  type: array
                  description: "Tags to apply to the Service and Task Definition"
                  items:
                    type: object
                    required: [key, value]
                    properties:
                      key:
                        type: string
                        title: Key
                      value:
                        type: string
                        title: Value
                  default:
                    - key: "ManagedBy"
                      value: "Backstage"
                    - key: "Environment"
                      value: "dev"  

                # ALB toggle
                enableLoadBalancer:
                  title: Expose service via Load Balancer
                  type: boolean
                  default: false

              required:
                - repoUrl
                - environment
                - ecsCluster
                - ecsServiceName
                - ecrRepository
                - containerName
                - containerPort
                - containerImage
                - cpu
                - memory
                - awsRegion

              dependencies:
                enableLoadBalancer:
                  oneOf:
                    - properties:
                        enableLoadBalancer:
                          const: true

                        vpcId:
                          title: VPC ID
                          type: string

                        targetGroupName:
                          title: Target Group Name
                          type: string

                        targetGroupPort:
                          title: Target Group Port
                          type: number
                          default: 8000

                        healthCheckPath:
                          title: Health Check Path
                          type: string
                          default: /health

                        loadBalancerName:
                          title: Load Balancer Name
                          type: string

                        albSecurityGroups:
                          title: ALB Security Groups
                          type: array
                          items:
                            type: string

                        certificateArn:
                          title: ACM Certificate ARN
                          type: string

                      required:
                        - vpcId
                        - targetGroupName
                        - targetGroupPort
                        - healthCheckPath
                        - loadBalancerName
                        - albSecurityGroups
                        - certificateArn

            # =====================================================
            # TRIGGER EXISTING WORKFLOW
            # =====================================================
            - properties:
                serviceMode:
                  const: trigger
              required:
                - repoUrl
                - environment

  ############################
  # STEPS
  ############################
  steps:
    # ---------------------------------------------------------
    # CREATE FLOW (AWS)
    # ---------------------------------------------------------
    - id: create-ecr
      if: ${{ parameters.serviceMode === 'create' }}
      name: Create ECR Repository
      action: aws:ecr:create
      input:
        repositoryName: ${{ parameters.ecrRepository }}
        region: ${{ parameters.awsRegion }}

    # ---------------------------------------------------------
    #  Create S3 Folder
    # ---------------------------------------------------------
    - id: create-s3-folder
      if: ${{ parameters.serviceMode === 'create' }}
      name: Create S3 Env Folder
      action: aws:s3:create-folder
      input:
        region: ${{ parameters.awsRegion }}
        bucketName: ${{ parameters.s3EnvBucket }}
        folderPath: ${{ parameters.s3EnvFolder }}

    - id: upload-env-file
      if: ${{ parameters.serviceMode === 'create' }}
      name: Create .env File in S3
      action: aws:s3:write-file
      input:
        region: ${{ parameters.awsRegion }}
        bucketName: ${{ parameters.s3EnvBucket }}
        path: ${{ parameters.s3EnvFolder }}/.env
        content: ${{ parameters.envFileContent }}  # <--- Passes the pasted text    

    # ---------------------------------------------------------
    #  Create Log Group
    # ---------------------------------------------------------
    - id: create-log-group
      if: ${{ parameters.serviceMode === 'create' }}
      name: Create CloudWatch Log Group
      action: aws:cloudwatch:create-log-group
      input:
        region: ${{ parameters.awsRegion }}
        logGroupName: ${{ parameters.logGroupName }}    

    - id: register-task-def
      if: ${{ parameters.serviceMode === 'create' }}
      name: Register ECS Task Definition
      action: aws:ecs:register-task-def
      input:
        family: ${{ parameters.ecsTaskDefName }}
        containerName: ${{ parameters.containerName }}
        containerPort: ${{ parameters.containerPort }}
        image: ${{ parameters.containerImage }}
        cpu: ${{ parameters.cpu }}
        memory: ${{ parameters.memory }}
        region: ${{ parameters.awsRegion }}
        executionRoleArn: ${{ 'arn:aws:iam::369521641981:role/ecsTaskExecutionRole' if parameters.environment == 'dev' else 'arn:aws:iam::270591008196:role/ecsTaskExecutionRole' }}
        taskRoleArn: ${{ 'arn:aws:iam::369521641981:role/ecsTaskExecutionRole' if parameters.environment == 'dev' else 'arn:aws:iam::270591008196:role/ecsTaskExecutionRole' }}
        command: ${{ parameters.commandOverride.split(' ') if parameters.commandOverride else [] }}
        environmentFiles:
          - value: arn:aws:s3:::${{ parameters.s3EnvBucket }}/${{ parameters.s3EnvFolder }}/.env
            type: s3
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: ${{ parameters.logGroupName }}
            awslogs-create-group: "true"
            awslogs-region: ${{ parameters.awsRegion }}
            awslogs-stream-prefix: "ecs" 
        tags: ${{ parameters.tags }}       

    # Create Target Group
    - id: create-target-group
      if: ${{ parameters.enableLoadBalancer }}
      name: Create Target Group
      action: aws:elbv2:create-target-group
      input:
        name: ${{ parameters.targetGroupName }}
        protocol: HTTP
        port: ${{ parameters.targetGroupPort }}
        vpcId: ${{ parameters.vpcId }}
        healthCheckPath: ${{ parameters.healthCheckPath }}
        region: ${{ parameters.awsRegion }}

    # Create ALB
    - id: create-alb
      if: ${{ parameters.enableLoadBalancer }}
      name: Create ALB
      action: aws:elbv2:create-alb
      input:
        name: ${{ parameters.loadBalancerName }}
        subnets: ${{ [
            'subnet-016f52b1842bd5240',
            'subnet-02116af62b70a6337',
            'subnet-0697eeb9e13c8a70b'
          ] if parameters.environment == 'dev' else [
            'subnet-ec8e64b5',
            'subnet-3b0f0513',
            'subnet-0d043e586ea16c604'
          ] }}
        securityGroups: ${{ parameters.albSecurityGroups }}
        region: ${{ parameters.awsRegion }}

    # HTTP Listener
    - id: create-http-listener
      if: ${{ parameters.enableLoadBalancer }}
      dependsOn:                
      - create-target-group
      - create-alb
      name: Create HTTP Listener
      action: aws:elbv2:create-listener
      input:
        loadBalancerArn: ${{ steps['create-alb'].output.loadBalancerArn }}
        port: 80
        protocol: HTTP
        targetGroupArn: ${{ steps['create-target-group'].output.targetGroupArn }}
        region: ${{ parameters.awsRegion }}

    # HTTPS Listener
    - id: create-https-listener
      if: ${{ parameters.enableLoadBalancer }}
      dependsOn:                
      - create-target-group
      - create-alb
      name: Create HTTPS Listener
      action: aws:elbv2:create-listener
      input:
        loadBalancerArn: ${{ steps['create-alb'].output.loadBalancerArn }}
        port: 443
        protocol: HTTPS
        certificateArn: ${{ parameters.certificateArn }}
        targetGroupArn: ${{ steps['create-target-group'].output.targetGroupArn }}
        region: ${{ parameters.awsRegion }}

    # ---------------------------------------------------------
    # CREATE ECS SERVICE
    # ---------------------------------------------------------
    - id: create-ecs-service
      if: ${{ parameters.serviceMode === 'create' }}
      dependsOn:                
      - create-target-group
      name: Create ECS Service
      action: aws:ecs:create-service
      input:
        cluster: ${{ parameters.ecsCluster }}
        serviceName: ${{ parameters.ecsServiceName }}
        region: ${{ parameters.awsRegion }}
        taskDefinition: "arn:aws:ecs:${{ parameters.awsRegion }}:${{ '369521641981' if parameters.environment == 'dev' else '270591008196' }}:task-definition/${{ parameters.ecsTaskDefName }}"
        subnets: ${{ [
            'subnet-0e9d3f1ad15c0ee74',
            'subnet-0e1a5c54a6d9fe52b',
            'subnet-093d89d1190420ba3',
            'subnet-04119f906b86b11ed',
            'subnet-07cc2e35a5592549c'
          ] if parameters.environment == 'dev' else [
            'subnet-3c0f0514',
            'subnet-8b795ffc',
            'subnet-ed8e64b4'
          ] }}

        securityGroups: ${{ [
            'sg-0313a6e7a7b90578c'
          ] if parameters.environment == 'dev' else [
            'sg-0c0a6611b141ad86d' 
          ] }}

        loadBalancers:
          - targetGroupArn: ${{ steps['create-target-group'].output.targetGroupArn }}
            containerName: ${{ parameters.containerName }}
            containerPort: ${{ parameters.targetGroupPort }}
        tags: ${{ parameters.tags }}    

    - id: register-service
      if: ${{ parameters.serviceMode === 'create' }}
      name: Register Service in Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: >-
          https://github.com/${{
            parameters.repoUrl
              | replace("github.com?owner=", "")
              | replace("&repo=", "/")
          }}/blob/${{ parameters.environment }}
        catalogInfoPath: /catalog-info.yaml
        optional: true

    # ---------------------------------------------------------
    # TRIGGER FLOW
    # ---------------------------------------------------------
    - id: trigger-deployment
      if: ${{ parameters.serviceMode === 'trigger' }}
      name: Trigger Deployment Workflow
      action: github:actions:dispatch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        workflowId: ecs-deploy-dev.yml
        branchOrTagName: dev
        workflowInputs:
          environment: ${{ parameters.environment }}

  ############################
  # OUTPUT
  ############################
  output:
    text:
      - title: ALB DNS Name
        content: |
          **${{ steps['create-alb'].output.dnsName }}**
    links:
      - title: Service URL
        url: https://${{ steps['create-alb'].output.dnsName }}
      - title: Open in Backstage Catalog
        icon: catalog
        entityRef: ${{ steps['register-service'].output.entityRef }}